joints:
  forearm_roll:
    effort: 999.99
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: False
  wrist_pitch:
    effort: 0.001
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: True
  # gripper:
  #   effort: 1.0
  #   gradual_startup_position: 0
  #   gradual_startup_time: 1.0
  #   antagonist: False
